name: Increment Maven Project Version

on:
  push:
    branches:
      - main

jobs:
  increment-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get the latest commit hash
        id: get-commit
        run: |
          echo "::set-output name=commit::$(git rev-parse --short HEAD)"
        shell: bash

      - name: Get the current version
        id: get-version
        run: |
          current_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "::set-output name=version::$current_version"
        shell: bash

      - name: Calculate the new version
        id: calculate-version
        run: |
          current_version=${{ steps.get-version.outputs.version }}
          commit_hash=${{ steps.get-commit.outputs.commit }}
          new_version="${current_version}-${commit_hash}"
          echo "::set-output name=version::$new_version"
        shell: bash

      - name: Update POM version
        run: |
          mvn versions:set -DnewVersion=${{ steps.calculate-version.outputs.version }}
