name: Release Maven Project

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Deploy to GitHub Packages
        run: |
          mvn -B release:prepare release:perform
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

      - name: Set Git Author Identity
        run: |
          git config user.name "${{ secrets.GITHUB_ACTOR }}"
          git config user.email "${{ secrets.GITHUB_ACTOR }}@users.noreply.github.com"

